n2n_v2: upgrade to v3
immortalwrt/packages pull request #400
Opened 2022-06-24 20:17 UTC by hecheng337

1. 整个包从 **n2n_v2** 重命名为 **n2n_v3**
2. 从 lean 仓库拉取了部分更新
3. 将IP动态伪装改为可选项

详见 [#198](https://github.com/immortalwrt/luci/pull/198)

2022-06-25 04:52 UTC, 1715173329 requested changes
这个可以考虑用 procd 实现进程守护，也避免了潜在的服务重载问题。
如果有空的话我今晚会处理一下。

2022-06-25 04:52 UTC, 1715173329 commented on net/n2n_v3/files/n2n_v3.init
> +        /usr/bin/edge -u 0 -g 0 -d $tunname -a ${mode}:${address} -c $community $([ -n "$key" ] && echo -k $key) -l ${supernode}:${port}$supernode_bak $args $mtu
```suggestion
        /usr/bin/edge -u 0 -g 0 -d $tunname -a ${mode}:${address} -c $community ${key:+-k $key} -l ${supernode}:${port}$supernode_bak $args $mtu
```

2022-06-25 05:26 UTC, 1715173329 commented
1. 没必要继续叫 n2n_xx，直接 n2n 就好了
2. supernode 和 edge 是否可以独立运行？这两个软件包都依赖同样的配置文件与 init，只为 edge 安装显然不合理。

2022-06-25 09:04 UTC, hecheng337 commented
> 这个可以考虑用 procd 实现进程守护，也避免了潜在的服务重载问题。 如果有空的话我今晚会处理一下。
> 
> EDIT：另外也可以考虑下用 cmake 编译，避开 autotools。

收到。
1. 确实应该独立开，现在这样只会越搞越乱。
    （我的想法是像 luci-app-openvpn 那样，用 luci-app-n2n 控制 n2n-edge ，用 luci-app-n2n-server 控制 n2n-supernode 。
2. v3版本号直接去掉也可以，应该没有用旧版本的需求。正好可以跟着前述一起改
3. 如果切换到 procd 的话，那个路由的设置可以直接使用 [n2n3.0 的新参数](https://github.com/ntop/n2n/blob/dev/doc/Routing.md)实现，又方便又不会出问题，没必要再手动添加了

2022-06-27 10:25 UTC, 1715173329 approved these changes

2022-06-29 22:51 UTC, merged